[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP2040 --protocol swd"
runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"

# [env]
# DEFMT_LOG = "debug"

[target.thumbv6m-none-eabi]
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    # "-C", "link-arg=-Tdefmt.x",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]
