theme = "rose_pine"

[editor]
line-number = "relative"
true-color = true
cursorline = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[keys.insert]
j = { k = "normal_mode" }

[editor.cursor-shape]
normal = "block"
select = "block"
insert = "block"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
"hidden" = false

[keys.normal]
C-s = [":fmt", ":w"]
C-f = ":fmt"
