theme = "tokyonight"

[editor]
true-color = true
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

