theme = "rose_pine"

[editor]
line-number = "relative"
true-color = true
cursorline = false
bufferline = "multiple"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
text-width = 80

[keys.insert]
j = { k = "normal_mode" }

[editor.cursor-shape]
normal = "block"
select = "block"
insert = "block"

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
"hidden" = false

[keys.normal]
C-s = [":fmt", ":w"]
C-f = ":fmt"
N = ":bn"
E = ":bc"

# line-up
C-e = ["keep_primary_selection","extend_line","yank","move_line_up","open_above","normal_mode","replace_with_yanked", "move_line_down", "move_line_down", "extend_line", "delete_selection", "move_line_up", "move_line_up"]
# line-down
C-g = ["keep_primary_selection","extend_line","delete_selection", "paste_after", "move_line_down"]
