[[language]]
name = "javascript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "vue"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-server = { command = "vue-language-server", args = ["--stdio"] }